[build]
builder = "nixpacks"
buildCommand = "npm install --prefix server && cd client && npm install && npm run build && cd .."

[deploy]
startCommand = "node server/src/index.js"
restartPolicyType = "on_failure"

[nixpacks]
nodejs = "20"
